import { COLORS, ORDER } from "../../../utils/globalConstans";

export interface Work {
  description: string;
  title: string;
  img: string;
  color: string;
  order: string;
  link: string;
}

export const WORK_LIST_HOME: Work[] = [
  {
    description: "Billboard Animal Welfare PSA",
    title: "Animal Welfare PSA",
    img: "/assets/images/work/imageBilbordPrva.png",
    color: COLORS.PALE_LEMON,
    order: ORDER.PICTURE_DOWN,
    link: "https://dribbble.com/shots/14976707-Billboard-Animal-Welfare-PSA",
  },
  {
    description: "Transport planning and management platform",
    title: "rouvia (previously, Forwardize)",
    img: "/assets/images/work/forwardizeImageDruga.png",
    color: COLORS.MISTY_ROSE,
    order: ORDER.PICTURE_UP,
    link: "https://rouvia.com/",
  },
  {
    description: "QClub application",
    title: "QCLUB",
    img: "/assets/images/work/qclubImageTreca.png",
    color: COLORS.CHAMPAGNE_PINK,
    order: ORDER.PICTURE_DOWN,
    link: "https://lnkd.in/d2qrjvGG",
  },
  {
    description: "cryptoCrazy Beavers - NFT Collection",
    title: "OpenSea",
    img: "/assets/images/work/nftGifCetvrti.png",
    color: COLORS.MISTY_ROSE,
    order: ORDER.PICTURE_UP,
    link: "https://dribbble.com/shots/17424751-cryptoCrazy-Beavers-NFT",
  },
  {
    description: "GetVoIP ■ website redesign",
    title: "GetVoIP",
    img: "/assets/images/work/getVoipImagePeta.png",
    color: COLORS.MAGNOLIA_DARK,
    order: ORDER.PICTURE_UP,
    link: "https://getvoip.com/",
  },
  {
    description:
      "From Scratch, a Washington DC-based food truck and catering business",
    title: "From Scratch",
    img: "/assets/images/work/fromScratchImageSesta.png",
    color: COLORS.MISTY_ROSE,
    order: ORDER.PICTURE_DOWN,
    link: "https://www.facebook.com/ffscratch",
  },
  {
    description: "Sekopak Instagram posts",
    title: "SekoPak",
    img: "/assets/images/work/sekopakImageSedma.png",
    color: COLORS.ALICE_BLUE,
    order: ORDER.PICTURE_UP,
    link: "https://sekopak.com/",
  },
  {
    description: "Dashboard project ■ aragon/blockchain app",
    title: "aragon/blockchain app",
    img: "/assets/images/work/jogiImageOsmi.png",
    color: COLORS.MINT_CREAM,
    order: ORDER.PICTURE_UP,
    link: "https://dribbble.com/shots/14907864-UI-UX-Dashboard-project",
  },
  {
    description: "CasinoGold app ■ main screens",
    title: "CasinoGold app",
    img: "/assets/images/work/profesorImageDeseta.png",
    color: COLORS.COSMIC_LATTE,
    order: ORDER.PICTURE_DOWN,
    link: "",
  },
  {
    description: "Euclid School ■ Landing Page",
    title: "quanthub",
    img: "/assets/images/work/profesorImageDeseta.png",
    color: COLORS.ALICE_BLUELIGHT,
    order: ORDER.PICTURE_UP,
    link: "https://dribbble.com/shots/14305872-Euclid-School-Landing-Page",
  },
  {
    description: "Music Player ■ Mobile app",
    title: "Random app",
    img: "/assets/images/work/profesorImageDeseta.png",
    color: COLORS.MISTY_ROSE,
    order: ORDER.PICTURE_UP,
    link: "https://dribbble.com/shots/14717391-Music-Player-Mobile-App",
  },
  {
    description: "Notorious Potato ■ Social Media",
    title: "Notorious Potato",
    img: "/assets/images/work/profesorImageDeseta.png",
    color: COLORS.MISTY_ROSE,
    order: ORDER.PICTURE_DOWN,
    link: "https://www.instagram.com/notoriouspotato_gr/",
  },
];

export const WORK_LIST_WORK: Work[] = [
  {
    description: "Billboard Animal Welfare PSA",
    title: "Animal Welfare PSA",
    img: "/assets/images/work/imageBilbordPrva.png",
    color: COLORS.PALE_LEMON,
    order: ORDER.PICTURE_DOWN,
    link: "https://dribbble.com/shots/14976707-Billboard-Animal-Welfare-PSA",
  },
  {
    description: "Transport planning and management platform",
    title: "rouvia (previously, Forwardize)",
    img: "/assets/images/work/forwardizeImageDruga.png",
    color: COLORS.MISTY_ROSE,
    order: ORDER.PICTURE_UP,
    link: "https://rouvia.com/",
  },
  {
    description: "QClub application",
    title: "QCLUB",
    img: "/assets/images/work/qclubImageTreca.png",
    color: COLORS.CHAMPAGNE_PINK,
    order: ORDER.PICTURE_DOWN,
    link: "https://lnkd.in/d2qrjvGG",
  },
  {
    description: "cryptoCrazy Beavers - NFT Collection",
    title: "OpenSea",
    img: "/assets/images/work/nftGifCetvrti.png",
    color: COLORS.MISTY_ROSE,
    order: ORDER.PICTURE_UP,
    link: "https://dribbble.com/shots/17424751-cryptoCrazy-Beavers-NFT",
  },
  {
    description: "GetVoIP ■ website redesign",
    title: "GetVoIP",
    img: "/assets/images/work/getVoipImagePeta.png",
    color: COLORS.MAGNOLIA_DARK,
    order: ORDER.PICTURE_UP,
    link: "https://getvoip.com/",
  },
  {
    description:
      "From Scratch, a Washington DC-based food truck and catering business",
    title: "From Scratch",
    img: "/assets/images/work/fromScratchImageSesta.png",
    color: COLORS.MISTY_ROSE,
    order: ORDER.PICTURE_DOWN,
    link: "https://www.facebook.com/ffscratch",
  },
  {
    description: "Sekopak Instagram posts",
    title: "SekoPak",
    img: "/assets/images/work/sekopakImageSedma.png",
    color: COLORS.ALICE_BLUE,
    order: ORDER.PICTURE_UP,
    link: "https://sekopak.com/",
  },
  {
    description: "Dashboard project ■ aragon/blockchain app",
    title: "aragon/blockchain app",
    img: "/assets/images/work/jogiImageOsmi.png",
    color: COLORS.MINT_CREAM,
    order: ORDER.PICTURE_UP,
    link: "https://dribbble.com/shots/14907864-UI-UX-Dashboard-project",
  },
  {
    description: "CasinoGold app ■ main screens",
    title: "CasinoGold app",
    img: "/assets/images/work/casinoImageDeveta.png",
    color: COLORS.COSMIC_LATTE,
    order: ORDER.PICTURE_DOWN,
    link: "https://apps.apple.com/ca/app/golden-casino-vegas-slots/id1216780424",
  },
  {
    description: "Euclid School ■ Landing Page",
    title: "quanthub",
    img: "/assets/images/work/profesorImageDeseta.png",
    color: COLORS.ALICE_BLUELIGHT,
    order: ORDER.PICTURE_UP,
    link: "https://dribbble.com/shots/14305872-Euclid-School-Landing-Page",
  },
  {
    description: "Music Player ■ Mobile app",
    title: "Random app",
    img: "/assets/images/work/musicappImageJedanajsta.png",
    color: COLORS.MISTY_ROSE,
    order: ORDER.PICTURE_UP,
    link: "https://dribbble.com/shots/14717391-Music-Player-Mobile-App",
  },
  {
    description: "Notorious Potato ■ Social Media",
    title: "Notorious Potato",
    img: "/assets/images/work/knedlaImageDvanajsta.png",
    color: COLORS.MISTY_ROSE,
    order: ORDER.PICTURE_DOWN,
    link: "https://www.instagram.com/notoriouspotato_gr/",
  },
  {
    description: "IT Security Website",
    title: "Avanet",
    img: "/assets/images/work/avanetWorkSection.jpeg",
    color: COLORS.LAVENDER,
    order: ORDER.PICTURE_UP,
    link: "https://www.behance.net/gallery/95255645/Avanet-Landing-Page",
  },
  {
    description: "Park City Granola",
    title: "Park City Granola",
    img: "/assets/images/work/parkCityWorkSection.jpeg",
    color: COLORS.CHAMPAGNE_PINK,
    order: ORDER.PICTURE_UP,
    link: "https://www.instagram.com/parkcitygranolaco/",
  },
  {
    description: "Halloween Page 404",
    title: "Hero page",
    img: "/assets/images/work/halloweenWorkSection.jpeg",
    color: COLORS.MISTY_ROSE,
    order: ORDER.PICTURE_UP,
    link: "https://www.instagram.com/p/CHBPJpLHOsH/?img_index=1",
  },
  {
    description: "Logo Collection",
    title: "Contura Design",
    img: "/assets/images/work/logosWorkSection.jpeg",
    color: COLORS.CHAMPAGNE_PINK,
    order: ORDER.PICTURE_DOWN,
    link: "https://dribbble.com/shots/14157514-Logo-universe-1",
  },
];
