export const COLORS = {
  GREEN: 'green',
  RED: 'red',
  BLUE: 'blue',

PALE_LEMON: '#FFFCEB',
LAVENDER_BLUSH: '#FFF2F2',
CHAMPAGNE_PINK:'E5D3CD',
GUNMETAL:'#16282F',
DARK_PASTEL_GREEN: '#52B44D',
LAVENDER: '#E1E4FF',
MAGNOLIA: '#F7F1FF',
MAGNOLIA_DARK: '#EAE6F1',
TEA_ROSE: '#FFC6C2',
JET: '#373435',
ALICE_BLUE: '#EAF5FF',
MINT_CREAM:' #EFFFFA',
COSMIC_LATTE: '#FFF8E3',
ALICE_BLUELIGHT: '#EEF9FF',
MISTY_ROSE: '#FFE5E3',
SEASHELL:'#FFEFE5',
}

export enum ORDER {
 PICTURE_UP = 'pictureUP',
 PICTURE_DOWN = 'pictureDOWN'
}